05-how-to-contribute-to-open-source.md
06-the-secret-sauce.md

- [ x ] 📝 Documentation Update
- Added more information about Highlighting your contributions
- Added step in practical application section
- [ x ] 🙅 no, because they aren't needed

Update course info

---

02-what-is-open-source.md

This PR updates the history of open source by providing a more accurate account of its origins. It includes the contribution of Christine Peterson in coining the term "open source software" and clarifies the role of Eric S. Raymond, Bruce Perens, and other developers in creating The Open Source Initiative (OSI).
- Fixes issue #9 
As mentioned in the statistic provided in the issue described above, open source is a male-dominated community. Clarifying that Christine Peterson originated the term would assure women and femme-identifying people that they have a place in open source. 
If possible, I'd like to see how many viewers that this information brought to the course, especially those who identify as woman or non-binary a couple of weeks (or months) after it's released. I want to …

feat: mentioning Christine Peterson

---

README.md

Corrected chapter label for hyperlink, Chapter 5 => Chapter 6
This PR fixes the README.md's text correction.

Update README.md: Label is wrongly referenced for link

---

05-how-to-contribute-to-open-source.md
07-conclusion.md
08-additional-resources.md

This PR fixes typos and adds additional resources to the project. The typos have been corrected to improve readability and maintain consistency. The additional resources provide more information and enhance the overall quality of the project. This PR aims to improve the user experience and ensure accurate and comprehensive content.
_Generated using [OpenSauced](https://opensauced.ai/)._

typos-fix in Chapters 5, 7, 8

---

09-glossary.md

This PR adds a new entry to the glossary: "Clone". It provides a clear definition of the term and explains the process of cloning a Git repository. The description also mentions the default behavior of the `git clone` command, which creates a reference to the remote repository called origin. This addition enhances the glossary by providing a comprehensive explanation of an important concept in Git.
_Generated using [OpenSauced](https://opensauced.ai/)._
Fixes #17

Add clone definition to glossary

---

.github/workflows/traige.yml

This PR adds the triage workflow to enable `.take` action on issues

ci: add `.take` action workflow action

---

01-intro.md
02-what-is-open-source.md
03-why-open-source.md
04-tools-to-be-successful.md
05-how-to-contribute-to-open-source.md
06-the-secret-sauce.md

This PR replaces all [Next Section ->](https://github.com/open-sauced/intro/blob/main/02-what-is-open-source.md) to [Next Section ->](02-what-is-open-source.md) on pages 1, 2, 3, 4, 5, and 6.

Next Section Links Updated

---

README.md

changed 'what is open source' to 'intro'
Update the link to the `intro` file in the README.md file to improve user experience and provide clear instructions for getting started with the course.
_Generated using [OpenSauced](https://opensauced.ai/)._
- [ ✅] 🙅 no, because they aren't needed
- [✅ ] 📜 README.md

updated the instructions for starting the course.

---

index.html

This PR adds an auto2top config to reset the scroll position when visiting another page.

Add auto2top config

---

06-the-secret-sauce.md

This PR removes the step of clicking the share button in the top right portion of the profile page and emphasizes the importance of sharing the resume to showcase open source contributions. Making this change would help users gain a better understanding of how OpenSauced's Chrome Extension can help them display 
their skills, especially for job interviews. 
Fixes #30

fix: revised parts of the open source resume section for clarity

---

LICENSE.txt
README.md

Add license and badge to repo.

docs: Add license

---

README.md

feat: Add contributing section

---

README.md

Added colon for language list in the course introduction.
Fixes #52

fix: add colon

---

README.md

Updated the README contributing guide to link to the contributing .md file from this repo
Closes #62 
clicking Contributing guide link now opens the internal contributing.md

#62 - Update README contributing guide to use the guide from this repo

---

06-the-secret-sauce.md
07-types-of-contributions.md
08-additional-resources.md
09-conclusion.md

In this PR I link rest of the pages form 06-secret-sauce to next button of respective pages.
Fixes #64

Fix Final Section Button Link Of Secret Sauce

---

CONTRIBUTING.md

Added the ".take" section to CONTRIBUTING.md
Closes #63
-nil-
-nil-
-nil-

added .take section to CONTRIBUTING.md

---

10-glossary.md

This PR adds about quality assurance and bug to the glossary. 
Fixes #61 
NO

Fix for Issue 61

---

10-glossary.md
CONTRIBUTING.md

This PR adds the feature for alphabetizing the glossary and adding alphabetization to the standard in the contributing guide for the glossary. 
Fixes #60 
**Alphabetical Glossary Recording:**
https://github.com/open-sauced/intro/assets/102450568/cbfc0d1e-b3d9-420f-b9ce-8eded24ff1be
**Contributions Update with a note for alphabetizing the glossary:**

Alphabatize glossary and add instructions to contributing guide.

---

README.md

This PR links the web version of the intro to the README file.
Closes [#89](https://github.com/open-sauced/intro/issues/89#issue-1981924952)

Add both options to view the course to the README.md

---

06-the-secret-sauce.md
README.md

This PR holds changes to update README as follow:
- Added the [Types of contributions](https://intro.opensauced.pizza/#/07-types-of-contributions) chapter to the [Course Overview](https://github.com/open-sauced/intro/blob/main/README.md#course-overview) section.
- Fixed wordings in text links.
- Fixed broken links.
- Added links.
- Fixed and adjusted wordings — also in [`06-the-secret-sauce.md`](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md#the-secret-sauce).
https://deploy-preview-94--sauced-intro.netlify.app/#/
Closes #93

docs: Update README

---

05-how-to-contribute-to-open-source.md

Remove the unwanted topics list from the "How to Contribute to Open Source" section. 
Fixes #101 
Before
After
Simply check the file to make sure the list topics are in fact removed.
None
None lol
Let me know if I missed anything, as I would be more than happy to make any necessary changes!

Remove necessary data in 'how to contribute' file

---

05-how-to-contribute-to-open-source.md

Closes #103 
1. Open the PR in GitPod
2. Use Live Server or Markdown Live Preview extension to see the suggested changes
3. Validate the changes, find any discrepancies and provide suggestions

docs: update `getting-started` guide

---

05-how-to-contribute-to-open-source.md

In a file , all (11) occurance of words [guest ,book] replaced with compounded word `"guestbook" ` .
Closes #105
It is my first PR ,I love it and mine dopamine is too high 😃

Created a consistency with guestbook term.

---

02-what-is-open-source.md
04-tools-to-be-successful.md
07-types-of-contributions.md
08-additional-resources.md
10-glossary.md

Replaced the "open-source" terms with "open source" without hyphen
Fixes #109

docs: replace open-source term

---

01-intro.md

Hello.
This pull request fixes the bugs present in the **01-intro.md** file.
As mentioned in #118, I have updated the following documentation changes:
`Welcome to the "Intro to Open Source with OpenSauced" course!`
`## Let's Get Started 🚀`
Hope these changes meet the necessary requirements.
If at all there are any changes to be made, then kindly let me know.
Thanks and Regards,
Mohit Kambli
Fixes #118.
None.
No testing required.
No
Happy.

Fix #118 : Bug: Fix wording in the Intro section

---

README.md
community-translations.md
i18n-guidelines.md

This PR creates a Community Translations section to provide a space where those willing to maintain translations in any language outside OpenSauced official translations can link to their translations.
Closes #117 
1. Navigate to Home Page and note the changes in the *Language Support* section.
2. Click the *Community Translations* link in the Language Support section to navigate to the new section.
3. Navigate to i18n Guidelines and note the changes in the *2. Community Translations* sections.
4. Click the *Community Translations* link in the Language Support section to navigate to the new section.

Add Community translations section

---

04-tools-to-be-successful.md

This PR fixes links, capitalization and wording adjustment in the "Tools to be Successful" chapter
- [] 🍕 Feature
Fixes https://github.com/open-sauced/intro/issues/129

Fix: Links, capitalization and wording adjustment in the "Tools to be Successful" chapter

---

.github/CODEOWNERS

This PR fixes the syntax format in CODEOWNERS file so that the code owners can be automatically added as reviewers.
Fixes #136

fix: format syntax in CODEOWNERS

---

07-types-of-contributions.md
_layouts/sidebar.md

This PR updates the "Types of Contributions" chapter with following changes:
- Updated the main and section titles.
- Moved the orphan article into the flow.
- Removed PR examples as some are irrelevant and for consistency throughout the chapter.
- Adjust wording and update content.
- Fixed format for better read.
Closes #130

docs: update the "Types of Contributions" chapter

---

04-tools-to-be-successful.md
05-how-to-contribute-to-open-source.md

This solves issue https://github.com/open-sauced/intro/issues/140 , where I added a note to fill PR form in lesson 05
Closes https://github.com/open-sauced/intro/issues/140
NA
NA

Added a note to fill PR form in lesson 05

---

CONTRIBUTING.md

This Pull Request adds an additional step to the CONTRIBUTING.md file.  Which explains to contributors that a new branch should be created before making changes to local repository clone. 
Step 4. was updated and its contents moved to step 5. which was added.
Closes #149 
no
happy face

feat: Add a step to create new branch in the CONTRIBUTING file

---

docs/intro-to-oss/additional-resources.md

This PR introduces a main title at the beginning and makes revisions to the "Additional Resources" section within the introductory open-source documentation. Specifically, it changes the wording in the first paragraph to enhance clarity and updates the capitalization of the "Blog Posts" subsection for consistency.
Fixes #163
Validate you see the thing working

fix: Add Title to 'Additional Resources' Page

---

docs/intro-to-oss/glossary.md

This PR fixes the 'duplication of the term "Docs" in the Glossary' bug 
Fixes #155 
Validate you see the thing working

fix: (docs) updated glossary.md

---

docs/intro-to-oss/how-to-contribute-to-open-source.md

Update the wording to encourage participants in creating an issue as part of open source working flow.
Fixes #146 
No visual changes
1. Go to `how-to-contribute-to-open-source.md`
2. Read the changed line **142**

fix: (doc) update the wording to create issue

---

docs/_sidebar.md

To get more awareness for starsearch, I added the CTA to the course.

feat: Add starsearch to sidebar

---

docs/intro-to-oss/translations/fr/_sidebar.md

Add OpenSauced logo to French sidebar for better user experience (UX).
**French Sidebar Update: Add OpenSauced Logo**
This pull request updates the French language sidebar (`_sidebar.md`) by adding the OpenSauced logo. This visual cue enhances the user experience (UX) for users navigating the French section.
Closes [#183](https://github.com/open-sauced/intro/issues/183)
1.  run `docsify serve docs`
2. Go to `docs/intro-to-oss/translations/fr/_sidebar.md`
3. Verify the OpenSauced Logo

feat: Add OpenSauced Logo to French Sidebar

---

docs/intro-to-oss/the-secret-sauce.md

Added the required sentence
This PR adds the required sentence after the full stop at line 75 in the code.
Closes #175 
1. Open the file [the-secret-sauce.md](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/the-secret-sauce.md) on GitHub.
2. Navigate to line 75.
3. Check if the required sentence has been added after the full stop at line 75.
4. If there are any issues or changes required, please provide details in the comments section of the PR.

feat: Adding a sentence

---

docusaurus.config.js
src/pages/index.js

We want to move the course location to opensauced.pizza/learn. This changes the config to serve from the /learn path.
closes #218 
1. go to http://localhost:3000/learn/

feat: Create a subdirectory structure 

---

docusaurus.config.js

The redirects weren't working, so we needed to change the url.
closes #229

fix: Change url to point to os.pizza

---

docs/becoming-a-maintainer/maintainers-guestbook.md

This PR adds a maintainer repository to existing maintainers guestbook list.
Relates to #199 
1. Click a link
2. Do this thing
3. Validate you see the thing working

feat: adds repo to guestbook

---

docs/intro-to-oss/how-to-contribute-to-open-source.md

This PR corrects a typo and grammatical mistakes in the 1st paragraph of "How to Contribute to Open Source"
Fixes #255 
_**Original (branch main):**_
_**PR will fix to display:**_
- Navigate to https://github.com/xjwllmsx/intro/blob/fix-typo/docs/intro-to-oss/how-to-contribute-to-open-source.md
- Note the first paragraph starts with: "One of the first challenges you might face when learning how to contribute to open source..."
- Note that the [original first paragraph](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/how-to-contribute-to-open-source.md) starts with: "One of the first challenges you might face when **getting** learning how to contribute **in** open source..."

fix: typo and grammatical issue

---

docusaurus.config.js

This small PR updates the copyright text from placeholder to Open Source Community.
Fixes #265.

fix: Update copyright text from placeholder to OpenSauced Community

---

contributing/CONTRIBUTING.md
contributing/community-translations.md
contributing/i18n-guidelines.md
docs/becoming-a-maintainer/additional-resources.md
docs/becoming-a-maintainer/building-community.md
docs/becoming-a-maintainer/communication-and-collaboration.md
docs/becoming-a-maintainer/community-translations.md
docs/becoming-a-maintainer/getting-practical.md
docs/becoming-a-maintainer/glossary.md
docs/becoming-a-maintainer/how-to-setup-your-project.md
docs/becoming-a-maintainer/issues-and-pull-requests.md
docs/becoming-a-maintainer/maintaining-code-quality.md
docs/becoming-a-maintainer/metrics-and-analytics.md
docs/intro-to-oss/additional-resources.md
docs/intro-to-oss/conclusion.md
docs/intro-to-oss/glossary.md
docs/intro-to-oss/how-to-contribute-to-open-source.md
docs/intro-to-oss/types-of-contributions.md
docs/intro-to-oss/what-is-open-source.md

This PR includes fixes after proofreading the .md files present in the repository. It is ensured that the flow, consistency remains intact. This also resolves grammatical and other bugs in the files.
Fixes #276 
🚀

docs: proofread and rectified errors
